name: javac

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      base: javac/
      main: Main.java
      run: Main
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk 
          architecture: x64 
      - run: |
          cd $base
          javac $main
          java $run
